quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls')),
]

quotes/quotesapp/urls.py
from django.urls import path

from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.main, name='main'),
    path("<int:page>", views.main, name='main_paginate'),
    path('tag/', views.tag, name='tag'),
    path('author/', views.author, name='author'),
    path('quote', views.quote, name = 'quote'),
    path('author_detail/<int:author_id>', views.author_detail, name='author_detail'),
    path('by_tag/<int:tag_id>', views.quotes_by_tag, name='by_tag'),
    path('by_tag/<int:tag_id>/<int:page>', views.quotes_by_tag, name='by_tag_paginate'),
    path('load_data', views.load_data, name='load_data'),
    path('load_check', views.load_check, name='load_check'),
]

quotes/users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', 
         views.ResetPasswordView.as_view(), 
         name='password_reset'),
    path('reset-password/done/', 
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/quotesapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count

# Create your models here.
    
class Tag(models.Model):
    name = models.CharField(max_length=35, null=False, unique=True)

    class Meta:
        db_table = "tags"

    def __str__(self):
        return f"{self.name}"
    
    @staticmethod
    def top_ten_tags():
        return Tag.objects.annotate(quotes_count=Count("quote")).order_by("-quotes_count")[:10]

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.DateField()
    born_location = models.CharField(max_length=150)
    description = models.CharField()
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    class Meta:
        db_table = "authors"

    def __str__(self):
        return f"{self.fullname}"

class Quote(models.Model):
    quote = models.CharField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    class Meta:
        db_table = "quotes"

    def __str__(self):
        return f"{self.quote[:20]}..."
    

quotes/quotesapp/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, Textarea, ModelChoiceField, ModelMultipleChoiceField
from .models import Tag, Author, Quote


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']

class AuthorForm(ModelForm):

    fullname = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    born_date = DateField()
    born_location = CharField(max_length=150)
    description = CharField(widget=Textarea(), required=False, strip=True)

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class QuoteForm(ModelForm):

    quote = CharField(min_length=10, max_length=150, required=True, widget=TextInput())
    author = ModelChoiceField(queryset=Author.objects.all())
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all())

    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']

quotes/quotesapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse

from .forms import TagForm, AuthorForm, QuoteForm
from .models import Author, Quote, Tag

import subprocess
from concurrent.futures import ThreadPoolExecutor

Pool = ThreadPoolExecutor(max_workers=1)
scrapper = []

RECORDS_PER_PAGE = 10

# Create your views here.
def main(request, page=1):
    quotes = Quote.objects.all()
    paginator = Paginator(quotes, RECORDS_PER_PAGE)
    paginator.get_page(page).previous_page_number
    return render(request, 'quotesapp/index.html', {'quotes': paginator.get_page(page),
                                                    "top_ten_tags": Tag.top_ten_tags()})

@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/tag.html', {'form': form})

    return render(request, 'quotesapp/tag.html', {'form': TagForm()})

@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save(commit=False)
            new_author.user = request.user
            new_author.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/author.html', {'form': form})
        
    return render(request, 'quotesapp/author.html', {'form': AuthorForm()})


def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotesapp/author_detail.html', {"author": author})


def quotes_by_tag(request, tag_id, page=1):
    tag = Tag.objects.get(pk=tag_id)
    quotes = Quote.objects.filter(tags__pk=tag_id)
    paginator = Paginator(quotes, RECORDS_PER_PAGE)
    return render(request, 'quotesapp/quotes_by_tag.html', {"quotes": paginator.get_page(page), 
                                                            "tag": tag,
                                                             "top_ten_tags": Tag.top_ten_tags()})


@login_required
def quote(request):
    authors = Author.objects.all()
    tags = Tag.objects.all()
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.user = request.user
            new_quote.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/quote.html', {'form': form, 'authors': authors, "tags": tags})
        
    return render(request, 'quotesapp/quote.html', {'form': QuoteForm(), 'authors': authors, "tags": tags})


@login_required
def load_data(request):
    command = 'python -m utils.scrap_and_load'
    if not scrapper:
        future = Pool.submit(subprocess.run, command, shell=True)
        scrapper.append(future)
    
    return JsonResponse({"success": True})

@login_required
def load_check(request):
    if not scrapper:
        return JsonResponse({"success": False, "not_loading": True})
    if scrapper and scrapper[0].done():
        scrapper.pop()
        return JsonResponse({"success": True})
    else:
        return JsonResponse({"success": False, "not_loading": False})

quotes/quotesapp/templates/quotesapp/author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:author' %}">
    {% csrf_token %}
    <div class="row">
        <label class="form-label"> Author's fullname:
            <input type="text" class="form-control" name="fullname">
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div class="row">
        <label class="form-label"> Author's date of birth:
            <input type="date" class="form-control" name="born_date" placeholder="mm/dd/yyyy" />
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div class="row">
        <label class="form-label"> Author's born location:
            <input type="text" class="form-control" name="born_location">
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div class="row">
        <label class="form-label"> Author's description:
            <textarea class="form-control" name="description" rows="3"></textarea>
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button class="btn btn-primary" type="submit">Submit</button>
        <button class="btn btn-primary" type="reset">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quotesapp/templates/quotesapp/author_detail.html
{% extends "quotesapp/base.html" %} 
{% block content %}

<div class="container">
<div class="row">
<div class="col-9">
<h1>{{author.fullname}}</h1>
<p>Born date: <kbd>{{author.born_date}}</kbd></p>
<p>Born location: <kbd>{{author.born_location}}</kbd></p>
<p>Description: <b>{{author.description}}</b></p>
</div>
</div>
</div>
{% endblock %}

quotes/quotesapp/templates/quotesapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body>
<div class="container">
     <div class="row header-box">
        <div class="col">
            <h1><a href="/" class="h1-title">Greate quotes</a></h1>
        </div>
        {% if user.is_authenticated %}
        <div class="col">
            <a href="{% url 'quotesapp:author' %}" role="button" class="btn btn-primary">Add author</a>
            <a href="{% url 'quotesapp:quote' %}" role="button" class="btn btn-primary">Add quote</a>
            <button class="btn btn-warning" id="load_data">Scrap and load</button>
        </div>
        <div class="col">
            Welcome <b>{{ user.username }}!</b>
            <a href="{% url 'users:logout' %}" role="button" class="btn btn-primary">Logout</a>
        </div>
        {% else %}
        <div class="col">
            <a href="{% url 'users:signup' %}" role="button" class="btn btn-primary">Sign Up</a>
            <a href="{% url 'users:login' %}" role="button"class="btn btn-primary">Login</a>
        </div>
        {% endif %}
    </div>
    <div id="liveAlertPlaceholder"></div>
    {% block content %} {% endblock %}
</div>
</body>
<script>
    $(document).ready(function () {
        $.ajax({
                type: "GET",
                url: "{% url 'quotesapp:load_check' %}",
                data:{},
                success: function(response){
                    const alertPlaceholder = document.getElementById('liveAlertPlaceholder')
                    const appendAlert = (message, type) => {
                    const wrapper = document.createElement('div')
                    wrapper.innerHTML = [
                        `<div id="success-alert" class="alert alert-${type} alert-dismissible" role="alert">`,
                        `   <div>${message}</div>`,
                        '   <button type="button" id="success-alert-close" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                        '</div>'
                    ].join('')

                    alertPlaceholder.append(wrapper)
                    }

                    if (response.success) {
                        appendAlert('Loading data successfully finished!', 'success')
                    } else {
                        if (!response.not_loading) {
                            appendAlert('Data loading in process!', 'warning')
                        }
                    }


                }
        })
    })
    $(function(){
        $('#load_data').click(function(){
            $.ajax({
                    url: "{% url 'quotesapp:load_data' %}",
                    type: "GET",
                    dataType: 'json',
                    data:{}
            })
        })
        
    })
</script>
</html>

quotes/quotesapp/templates/quotesapp/data_load.html
{% extends "quotesapp/base.html" %}
{% block content %}
<div class="progress" role="progressbar" aria-label="Basic example" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
    <div class="progress-bar" style="width: 25%"></div>
</div>
{% endblock %}

quotes/quotesapp/templates/quotesapp/index.html
{% extends "quotesapp/base.html" %}
{% load extra_tags %}
{% block content %}
    <div class="container">
      <div class="row">
        <div class="col-8">
        {% for quote in quotes %}
        <div class="quote">
          <h3>{{ quote.quote }}</h3>
          <p class="tags">by {{ quote.author.fullname }}
            <a href="{% url 'quotesapp:author_detail' quote.author.id %}">(about)</a>
          </p>
          <p>Tags: 
            {% for tag in quote.tags.all %}
            <a href="{% url 'quotesapp:by_tag' tag.id %}" class="tag"> {{ tag.name }} </a>
            {% endfor%}
          </p>
        </div>
        {% endfor %}
        <nav>
          <ul class="pagination justify-content-end">
            {% if quotes.has_previous %}
            <li class="page-item">
              <a href="{% url 'quotesapp:main_paginate' quotes.previous_page_number %}" class="page-link"><span aria-hidden="true">←</span> Previous</a>
            </li>
            {% endif %}
            {% if quotes.has_next %}
            <li class="page-item">
              <a href="{% url 'quotesapp:main_paginate' quotes.next_page_number %}" class="page-link">Next <span aria-hidden="true">→</span></a>
            </li>
            {% endif %}
          </ul>
        </nav>
        </div>
        <div class="col-4 tags-box">
        <h2>Top Ten Tags</h2>
        {% with 28|toptenrate:top_ten_tags as top_ten %}
        {% for tag in top_ten %}
        <span class="tag-item">
          <a href="{% url 'quotesapp:by_tag' tag.id %}" class="tag" style="font-size: {{ tag.font }}px;">{{ tag.name }}</a>
        </span>
        {% endfor %}
        {% endwith %}
        </div>
      </div>
    </div>
{% endblock %}

quotes/quotesapp/templates/quotesapp/quote.html
{% extends "quotesapp/base.html" %}

{% block content %}
<form method="POST" action="{% url 'quotesapp:quote' %}">
    {% csrf_token %}
    <div class="row mb-3">
        <label class="form-label"> Quote:
            <input type="text" class="form-control" name="quote">
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div class="row mb-3">
        <label> Author:
            <select name="author" class="form-select">
                {% for author in authors %}
                <option value="{{ author.id }}">{{ author.fullname }}</option>
                {% endfor %}
            </select>
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div class="row mb-3">
        <label> Select tags:
            <select name="tags" class="form-select" multiple>
                {% for tag in tags %}
                <option value="{{ tag.id }}">{{ tag.name }}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quotesapp/templates/quotesapp/quotes_by_tag.html
{% extends "quotesapp/base.html" %}
{% load extra_tags %}
{% block content %}
    <h2 class="quotes-by-tag">Quotes by tag: {{ tag.name }}</h2>
    <div class="container">
      <div class="row">
        <div class="col-8">
        {% for quote in quotes %}
        <div class="quote">
          <h3>{{ quote.quote }}</h3>
          <p class="tags">by {{ quote.author.fullname }}
            <a href="{% url 'quotesapp:author_detail' quote.author.id %}">(about)</a>
          </p>
          <p>Tags: 
            {% for tag in quote.tags.all %}
            <a href="{% url 'quotesapp:by_tag' tag.id %}" class="tag"> {{ tag.name }} </a>
            {% endfor%}
          </p>
        </div>
        {% endfor %}
        <nav>
          <ul class="pagination justify-content-end">
            {% if quotes.has_previous %}
            <li class="page-item">
              <a href="{% url 'quotesapp:by_tag_paginate' tag.id quotes.previous_page_number %}" class="page-link"><span aria-hidden="true">←</span> Previous</a>
            </li>
            {% endif %}
            {% if quotes.has_next %}
            <li class="page-item">
              <a href="{% url 'quotesapp:by_tag_paginate' tag.id quotes.next_page_number %}" class="page-link">Next <span aria-hidden="true">→</span></a>
            </li>
            {% endif %}
          </ul>
        </nav>
        </div>
        <div class="col-4 tags-box">
        <h2>Top Ten Tags</h2>
        {% with 28|toptenrate:top_ten_tags as top_ten %}
        {% for tag in top_ten %}
        <span class="tag-item">
          <a href="{% url 'quotesapp:by_tag' tag.id %}" class="tag" style="font-size: {{ tag.font }}px;">{{ tag.name }}</a>
        </span>
        {% endfor %}
        {% endwith %}
        </div>
      </div>
    </div>
{% endblock %}

quotes/quotesapp/templates/quotesapp/tag.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}